//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagementAssignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class product
    {
        public int ProductId { get; set; }
        
        [Required(ErrorMessage = "Name is a required field")]
        public string Name { get; set; }
        
        [Required(ErrorMessage = "Category is a required field")]
        public string Category { get; set; }
        
        [Required(ErrorMessage = "Price is a required field")]
        public long Price { get; set; }
        
        [Required(ErrorMessage = "Quantity is a required field")]
        public int Quantity { get; set; }
        
        [Required(ErrorMessage = "Description is a required field")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Image is a required field")]
        public string Image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
