//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourceControlAssignment {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txt_fn;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox txt_ln;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox txt_email;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
		
		protected System.Web.UI.WebControls.TextBox txt_password;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.TextBox txt_cpassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
		
		protected System.Web.UI.WebControls.CompareValidator CompareValidator1;
		
		protected System.Web.UI.WebControls.TextBox txt_age;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
		
		protected System.Web.UI.WebControls.TextBox txt_roll;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;
		
		protected System.Web.UI.WebControls.RangeValidator RangeValidator2;
		
		protected System.Web.UI.WebControls.TextBox txt_mn;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator8;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator2;
		
		protected System.Web.UI.WebControls.Button btn;
		
		protected System.Web.UI.WebControls.Label Label1;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Label Label3;
		
		protected System.Web.UI.WebControls.Label Label4;
		
		protected System.Web.UI.WebControls.Label Label5;
	}
}
